-- MySQL Script generated by MySQL Workbench
-- 09/15/14 09:41:00
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mibasededatos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mibasededatos` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mibasededatos` ;

-- -----------------------------------------------------
-- Table `mibasededatos`.`persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mibasededatos`.`persona` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `apellido` VARCHAR(150) NOT NULL,
  `nombre` VARCHAR(150) NOT NULL,
  `dni` INT NOT NULL,
  `fecha_nacimiento` DATE NULL,
  `creado` DATETIME NULL,
  `biografia` TEXT NULL,
  `vive` TINYINT(1) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `dni_UNIQUE` (`dni` ASC),
  INDEX `apenom` (`apellido` ASC, `nombre` ASC),
  INDEX `fecha` (`fecha_nacimiento` ASC))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `mibasededatos`.`provincia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mibasededatos`.`provincia` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `mibasededatos`.`departamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mibasededatos`.`departamento` (
  `idlocalidad` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(150) NULL,
  `provincia_id` INT NOT NULL,
  PRIMARY KEY (`idlocalidad`),
  INDEX `fk_departamento_provincia1_idx` (`provincia_id` ASC))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `mibasededatos`.`direccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mibasededatos`.`direccion` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `calle` VARCHAR(45) NULL,
  `numero` INT NULL,
  `piso` INT NULL,
  `depto` VARCHAR(5) NULL,
  `persona_id` INT UNSIGNED NOT NULL,
  `departamento_idlocalidad` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_direccion_persona_idx` (`persona_id` ASC),
  INDEX `fk_direccion_departamento1_idx` (`departamento_idlocalidad` ASC))
ENGINE = MyISAM;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
